Action()
{
	int flight_id_num = 0;
	
    lr_start_transaction("UC_3_CancelTicket");
	
	lr_start_transaction("go_to_site");
	
	web_set_sockets_option("SSL_VERSION", "AUTO");
	
	web_add_auto_header("Sec-Fetch-Site", 
		"none");

	web_add_auto_header("Sec-Fetch-Dest", 
		"document");

	web_add_auto_header("Sec-Fetch-Mode", 
		"navigate");

	web_add_auto_header("Sec-Fetch-User", 
		"?1");

	web_add_auto_header("Upgrade-Insecure-Requests", 
		"1");

/*Correlation comment: Automatic rules - Do not change!  
Original value='129608.097286351zzzzHVzpfAtVzzzHtAAAApcQQAcf' 
Name ='userSession' 
Type ='Rule' 
AppName ='WebTours' 
RuleName ='AutoGeneratedRuleName_UserSession'*/
	web_reg_save_param_attrib(
		"ParamName=userSession",
		"TagName=input",
		"Extract=value",
		"Name=userSession",
		"Type=hidden",
		SEARCH_FILTERS,
		"RequestUrl=*/nav.pl*",
		LAST);
		
		web_reg_find("Fail=NotFound",
		"Text=A Session ID has been created and loaded into a cookie called MSO.",
		LAST);

	web_url("WebTours", 
		"URL=http://localhost:1080/WebTours/", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=", 
		"Snapshot=t1.inf", 
		"Mode=HTML", 
		LAST);
		
		lr_end_transaction("go_to_site",LR_AUTO);

	/*Possible OAUTH authorization was detected. It is recommended to correlate the authorization parameters.*/

	lr_start_transaction("login");

	web_revert_auto_header("Sec-Fetch-User");

	web_add_auto_header("Sec-Fetch-Dest", 
		"frame");

	web_revert_auto_header("Upgrade-Insecure-Requests");

	web_add_header("Origin", 
		"http://localhost:1080");

	web_add_auto_header("Sec-Fetch-Site", 
		"same-origin");

	lr_think_time(6);
	
	web_reg_find("Fail=NotFound",
		"Text=User password was correct",
		LAST);

	web_submit_data("login.pl",
		"Action=http://localhost:1080/cgi-bin/login.pl",
		"Method=POST",
		"TargetFrame=body",
		"RecContentType=text/html",
		"Referer=http://localhost:1080/cgi-bin/nav.pl?in=home",
		"Snapshot=t2.inf",
		"Mode=HTML",
		ITEMDATA,
		"Name=userSession", "Value={userSession}", ENDITEM,
		"Name=username", "Value={login}", ENDITEM,
		"Name=password", "Value={password}", ENDITEM,
		"Name=login.x", "Value=55", ENDITEM,
		"Name=login.y", "Value=5", ENDITEM,
		"Name=JSFormSubmit", "Value=off", ENDITEM,
		LAST);

	lr_end_transaction("login",LR_AUTO);

	lr_start_transaction("click_itinerary");

	web_add_auto_header("Sec-Fetch-User", 
		"?1");

	web_add_auto_header("Upgrade-Insecure-Requests", 
		"1");

	lr_think_time(26);
	
	web_reg_save_param("flights_numbers",
		"LB=<b>A total of",
		"RB= scheduled flights.</font></b>",
		LAST);
	
	web_reg_find("Fail=NotFound",
		"Text=Web Tours Navigation Bar",
		LAST);

	web_url("Itinerary Button",
		"URL=http://localhost:1080/cgi-bin/welcome.pl?page=itinerary",
		"TargetFrame=body",
		"Resource=0",
		"RecContentType=text/html",
		"Referer=http://localhost:1080/cgi-bin/nav.pl?page=menu&in=home",
		"Snapshot=t3.inf",
		"Mode=HTML",
		LAST);
	
	flight_id_num = atoi(lr_eval_string("{flights_numbers}"));

	lr_end_transaction("click_itinerary",LR_AUTO);

	lr_start_transaction("choose_and_cancel_itinerary");

	web_add_header("Origin", 
		"http://localhost:1080");

	lr_think_time(152);
	
	web_reg_find("Fail=NotFound",
		"Text=Flights List",
		LAST);
	
	web_submit_form("web_submit_form",
		ITEMDATA,
		"Name=1", "Value=on", ENDITEM,
		"Name=removeFlights.x", "Value=67", ENDITEM,
		"Name=removeFlights.y", "Value=12", ENDITEM,
		EXTRARES,
		"URL=http://localhost:1080/cgi-bin/itinerary.pl",
		"Referer=http://localhost:1080/cgi-bin/itinerary.pl",
		ENDITEM,
		LAST);
	
	if (atoi(lr_eval_string("{flights_numbers}")) > flight_id_num ){
		
		lr_error_message("Itinerary not deleted!");
		
	} else if (atoi(lr_eval_string("{flights_numbers}")) < flight_id_num ){
		
		lr_output_message("Itinerary deleted!");	
	}
	
	lr_end_transaction("choose_and_cancel_itinerary",LR_AUTO);

	lr_start_transaction("logout");

	web_revert_auto_header("Sec-Fetch-User");

	web_add_header("Sec-Fetch-User", 
		"?1");

	lr_think_time(21);
	
	web_reg_find("Fail=NotFound",
		"Text= A Session ID has been created and loaded into a cookie called MSO.",
		LAST);

	web_url("SignOff Button",
		"URL=http://localhost:1080/cgi-bin/welcome.pl?signOff=1",
		"TargetFrame=body",
		"Resource=0",
		"RecContentType=text/html",
		"Referer=http://localhost:1080/cgi-bin/nav.pl?page=menu&in=itinerary",
		"Snapshot=t5.inf",
		"Mode=HTML",
		LAST);

	lr_end_transaction("logout",LR_AUTO);

	lr_end_transaction("UC_3_CancelTicket",LR_AUTO);

	return 0;
}